import type { Metadata } from "next";
import { Geist, Geist_Mono,Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header"
import Footer from "./components/Footer"

export const metadata: Metadata = {
  title: "stream verse",
  description: "Generated by create next app",
};
const poppins = Poppins({
  weight: ['400', '500', '600', '700'], // Choose the weights you need
  subsets: ['latin'],
  display: 'swap',
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={poppins.variable}
      
    >
      
      <body className="min-h-full flex flex-col">
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
