import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "stream verse",
  description: "Generated by create next app",
  icons: {
    icon: "./icon.png",
  },
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className=" flex flex-col max-w-full mx-auto min-h-screen">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
